name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.1.1
  firebase_storage: 12.4.10
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
assets:
  - images/profile_picture.png
  - images/google.jpg
  - images/iphone-15.jpg
  - images/samsung.jpg



flutter:
  uses-material-design: true
