name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.6.1
  firebase_storage: ^11.5.0
  google_sign_in: ^6.1.5
  provider: ^6.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
assets:
  - images/profile_picture.png
  - images/google.jpg
  - images/iphone-15.jpg
  - images/samsung.jpg



flutter:
  uses-material-design: true
